#!/bin/bash -l

function lock {
    if [ -z $1 ]; then
        echo 'No lock given to unlock!'
        exit 1;
        
    fi
    LOCK=$1

    echo "Acquiring lock: $LOCK"
    if [ -e $LOCK ]; then
        failure_do_not_unlock "Lock exists! Cannot continue!"
    fi
    # lock
    touch $LOCK
    if [ ! -e $LOCK ]; then
        failure_do_not_unlock "Failed to acquire lock!"
    fi
    echo "Lock acquired."
}

function unlock {
    if [ -z $1 ]; then
        echo 'No lock given to unlock!'
        exit 1;
    fi

    rm -f $LOCK
    echo "Lock removed."
}

