#!/bin/bash -l

function set_lock {
    if [ -z $1 ]; then
        echo 'No lock to given to set!'
        exit 1;
    fi
    export LOCK=$1
}

function lock {
    if [ ! -z $1 ]; then
        set_lock $1
    fi

    if [ -z $LOCK ]; then
        echo 'No lock set to lock!'
        exit 1;
    fi

    echo "Acquiring lock: $LOCK"
    if [ -e $LOCK ]; then
        failure_do_not_unlock "Lock exists! Cannot continue!"
    fi

    touch $LOCK
    if [ ! -e $LOCK ]; then
        failure_do_not_unlock "Failed to acquire lock!"
    fi
}

function unlock {
    if [ -z $LOCK ]; then
        echo 'No lock set to unlock!'
        exit 1;
    fi

    echo "Removing lock: $LOCK"
    rm -f $LOCK
}

function locked {
    if [ -z $LOCK ]; then
        echo 'No lock set to check!'
        exit 1;
    fi

    if [ -e $LOCK ]; then
        return 1;
    fi
    return 0;
}

