#!/bin/bash -l

function lock {
    if [ -z $LOCK ]; then
        echo 'NO LOCK set!'
        exit 1;
    fi

    echo "Acquiring lock: $LOCK"
    if [ -e $LOCK ]; then
        failure_do_not_unlock "Lock exists! Cannot continue!"
    fi

    touch $LOCK
    if [ ! -e $LOCK ]; then
        failure_do_not_unlock "Failed to acquire lock!"
    fi
}

function unlock {
    if [ -z $LOCK ]; then
        echo 'No LOCK setunlock!'
        exit 1;
    fi

    echo "Removing lock: $LOCK"
    rm -f $LOCK
}

function locked {
    if [ -z $LOCK ]; then
        echo 'No LOCK setunlock!'
        exit 1;
    fi

    if [ -e $LOCK ]; then
        return 1;
    fi
    return 0;
}

