#!/bin/bash -l

# be noisy to debug
#set -x

# SETUP
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $SCRIPT_DIR/exiting
if [ $? -ne 0 ]; then exit; fi
was_help_requested $1
. $SCRIPT_DIR/locking
if [ $? -ne 0 ]; then exit; fi

# CHECK DB
if [ -z $DB ]; then
    echo "No database given!"
    echo $USAGE
    exit 1;
fi

if [ "$DB" != 'nt' -a "$DB" != 'nr' ]; then
    echo "Invalid database! $DB" 
    echo $USAGE
    exit 1;
fi

# PATHS
export BASE_PATH='/gscmnt/gc2103/info/annotation/genbank_nrnt'
export FINAL_DB_PATH=$BASE_PATH'/'$DB'.gz'
export DB_PATH_UNZIPPED=$BASE_PATH'/'$DB
export WORKSPACE_PATH=$BASE_PATH'/.'$DB

export RSYNC_PATH=$WORKSPACE_PATH'/rsync'
export RSYNC_DB_PATH=$RSYNC_PATH'/'$DB'.gz'
export RSYNC_TMP_DB_PATH=$RSYNC_PATH'/__'$DB'__.gz' # for copy/move
export GUNZIP_PATH=$WORKSPACE_PATH'/gunzip'
export GUNZIP_VERSION_PATH=$GUNZIP_PATH'/version'
export XDFORMAT_PATH=$WORKSPACE_PATH'/xdformat'
export XDFORMAT_VERSION_PATH=$XDFORMAT_PATH'/version'

# LOCK TODO lock automatically, need to figure out what the lock is
#lock 
