#!/bin/bash -l

# be noisy to debug
#set -x

# SETUP
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $SCRIPT_DIR/exiting
if [ $? -ne 0 ]; then exit; fi
was_help_requested $1
. $SCRIPT_DIR/locking
if [ $? -ne 0 ]; then exit; fi

# CHECK DB
if [ -z $DB ]; then
    echo "No database given!"
    echo $USAGE
    exit 1;
fi

if [ "$DB" != 'nt' -a "$DB" != 'nr' ]; then
    echo "Invalid database! $DB" 
    echo $USAGE
    exit 1;
fi

# PATHS
export BASE_PATH='/gscmnt/gc2103/info/annotation/genbank_nrnt'
export WORKSPACE_BASE_PATH=$BASE_PATH'/.'$DB
export WORKSPACE_DB_PATH=$WORKSPACE_BASE_PATH'/'$DB'.gz'
export WORKSPACE_DB_MODIFIED_PATH=$WORKSPACE_BASE_PATH'/last-modified'
export WORKSPACE_TMP_DB_PATH=$WORKSPACE_BASE_PATH'/__'$DB'__.gz' # for copy/move
export WORKSPACE_GUNZIP_PATH=$WORKSPACE_BASE_PATH'/gunzip'
export WORKSPACE_GUNZIP_VERSION_PATH=$WORKSPACE_BASE_PATH'/gunzip/version'
export WORKSPACE_XDFORMAT_PATH=$WORKSPACE_BASE_PATH'/xdformat'
export WORKSPACE_XDFORMAT_VERSION_PATH=$WORKSPACE_BASE_PATH'/xdformat/version'
export FINAL_DB_PATH=$BASE_PATH'/'$DB'.gz'
export DB_PATH_UNZIPPED=$BASE_PATH'/'$DB

# LOCK TODO lock automatically, need to figure out what the lock is
#lock 
