#!/bin/bash -l

# CHECK DB
if [ -z $DB ]; then
    echo "No database given!"
    echo $USAGE
    exit 1;
fi

if [ "$DB" != 'nt' -a "$DB" != 'nr' ]; then
    echo "Invalid database! $DB" 
    echo $USAGE
    exit 1;
fi

# PATHS
export BASE_PATH='/gscmnt/gc2103/info/annotation/genbank_nrnt'
export WORKSPACE_BASE_PATH=$BASE_PATH'/.'$DB
export WORKSPACE_DB_PATH=$WORKSPACE_BASE_PATH'/'$DB'.gz'
export WORKSPACE_DB_SIZE_PATH=$WORKSPACE_BASE_PATH'/'$DB'.gz.size'
export WORKSPACE_TMP_DB_PATH=$WORKSPACE_BASE_PATH'/__'$DB'__.gz' # for copy/move
export FINAL_DB_PATH=$BASE_PATH'/'$DB'.gz'

# LOCKS
export LOCK=$WORKSPACE_BASE_PATH'/lock'

