#!/gsc/bin/perl

use strict;
use warnings;
use MIME::Lite;

use Users;

my $hudson_build_number = $ENV{BUILD_NUMBER};
my $hudson_build_url = join('/', 'http://hudson:8090/job/Diff%20Test', $hudson_build_number);

my $passed_model_tests_dir = "/gsc/scripts/opt/passed-model-tests";
my @snapshots = glob("$passed_model_tests_dir/*");

print "Found " . scalar @snapshots . " snapshots in $passed_model_tests_dir\n";

# Get the most recent snapshot in the passed-model-tests directory, which
# should the snapshot that was just created by the nightly model test process
# TODO Use the sqlite database Justin is setting up instead of this
my $latest_hudson_id = 0;
my $latest_snapshot_path;
for my $snapshot (@snapshots) {
    $snapshot =~ /.*genome-(\d+).*/;
    my $id = $1;
    if ($id > $latest_hudson_id) {
        $latest_hudson_id = $id;
        $latest_snapshot_path = $snapshot;
    }
}
$latest_snapshot_path .= "/lib/perl";

my $stable = readlink("/gsc/scripts/opt/genome-stable");
print "Latest snapshot seems to be $latest_snapshot_path, diffing against current genome-stable $stable\n";

#my $diff_cmd = "perl -I $latest_snapshot_path `which gmt` compare-builds --first-revision " .
#    "$latest_snapshot_path apipe-test%";
my $diff_cmd = "perl -I /gscuser/bdericks/genome/clean/lib/perl `which gmt` compare-builds --first-revision " .
    "$latest_snapshot_path apipe-test%";

my $diff_out = eval { `$diff_cmd 2>&1` };
if ($@ or $?) {
    my $exit_code = $@ ? $@ : ($? >> 8);
    print "Problems executing diff command\nExit code: $exit_code\nOutput:\n$diff_out";
    my $failure_msg_body = "Hudson diff build $hudson_build_number failed to execute! To see raw output, go to $hudson_build_url";
    send_mail(subject => '[fail] Test Build Diff Failed to Execute!', body => $failure_msg_body);
    exit 1;
}

print "Diff command output:\n$diff_out\n";

if ($diff_out =~ /DIFFERENCES FOUND:/) {
    print "Diff found that some files were not the same, sending email!\n";
    my $failure_msg_body = "Output diff between hudson nightly test builds running on $latest_snapshot_path " .
        "and genome-stable ($stable) found differences!\nTo see raw output, go to $hudson_build_url";
    send_mail(subject => '[fail] Test Build Diff Failed!', body => $failure_msg_body);
    exit 1;
}

print "Test build differ completed successfully and no differences found!\n";
print "Fin.\n";
exit 0;

sub send_mail {
    my %params = @_;
    my $subject = $params{subject} || die "No subject provided to send_mail method!";
    my $data = $params{body} || die "No messsage body provied to send_mail method!";
    my $from = $params{from} || sprintf('%s@genome.wustl.edu', $ENV{'USER'});
    #my $to = $params{to} || join(",", map { $_ . '@genome.wustl.edu' } Users::apipe());
    my $to = 'bdericks@genome.wustl.edu';
    my $msg = MIME::Lite->new(
        From => $from,
        To => $to,
        Subject => $subject,
        Data => $data,
    );
    $msg->send();
}
