#!/bin/bash -x

set -o errexit   # exit if any command fails
set -o pipefail  # fail if any command in a pipe fails
set -o nounset   # fail if an env var is used but unset

# run from "deploy" host

DEPLOY_PATH="/gsc/scripts/opt"
HUDSON_CODE_PATH="/gscuser/jlolofie/dev/wugc-hudson-dev"

OLD_BUILD_NAME=`perl -e '$path = readlink("/gsc/scripts/opt/genome-stable"); $path =~ s/.*\///; print $path'`
OLD_BUILD_VERSION=`echo $OLD_BUILD_NAME | sed 's/-fix.*//'`

if [ -n "${1+x}" ]; then
    BUILD_NUMBER=$1
    NEW_BUILD_NAME="genome-$BUILD_NUMBER"
    NEW_BUILD_VERSION=`echo $NEW_BUILD_NAME | sed 's/-fix.*//'`
    BUILD_PATH="./passed-model-tests/$NEW_BUILD_NAME"
else
    echo "Error: first arg should be a hudson genome build number"
    exit
fi

cd $DEPLOY_PATH

if [ ! -d $BUILD_PATH ]; then
    echo "Error: cant find build path: \"$BUILD_PATH\""
    exit
fi


echo "Changing stable symlink ($NEW_BUILD_NAME)"
ln -s $BUILD_PATH new-genome-stable
mv -Tf new-genome-stable genome-stable


echo "Changing web symlink (needs a restart)"
ln -s $BUILD_PATH new-genome-webapp
mv -Tf new-genome-webapp genome-webapp


perl $HUDSON_CODE_PATH/tools/changelog.pl $OLD_BUILD_VERSION $NEW_BUILD_VERSION > $DEPLOY_PATH/git-changes
if [ -f $DEPLOY_PATH/hotfixes ]; then
    echo 'Hotfixes:' > $DEPLOY_PATH/CHANGES
    cat $DEPLOY_PATH/hotfixes >> $DEPLOY_PATH/CHANGES
fi
if [ -f $DEPLOY_PATH/git-changes ]; then
    cat $DEPLOY_PATH/git-changes >> $DEPLOY_PATH/CHANGES
fi
if [ -f $DEPLOY_PATH/CHANGES ]; then
    if [ -n "$USER" ]; then
        USER_NAME=$USER
    else
        USER_NAME=apipe-tester
    fi
    echo "Subject: Changes for $NEW_BUILD_NAME " | cat - $DEPLOY_PATH/CHANGES | sendmail -F $USER_NAME@genome.wustl.edu -t apipe@genome.wustl.edu
fi

