#!/bin/bash -x

set -o errexit   # exit if any command fails
set -o pipefail  # fail if any command in a pipe fails
set -o nounset   # fail if an env var is used but unset


# run from "deploy" host


DEPLOY_PATH="/gsc/scripts/opt"
HUDSON_CODE_PATH="/gscuser/jlolofie/dev/wugsc-hudson-dev"

OLD_BUILD_NAME=`ls -l /gsc/scripts/opt/genome-stable | perl -e '$j=<>; $j=~/(genome-\d+)/; print $1'`

if [ -n "${1+x}" ]; then
    BUILD_NUMBER=$1
    NEW_BUILD_NAME="genome-$BUILD_NUMBER"
    BUILD_PATH="./passed-model-tests/$BUILD_NAME"
else
    echo "Error: first arg should be a hudson genome build number"
    exit
fi

cd $DEPLOY_PATH

if [ ! -d $BUILD_PATH ]; then
    echo "Error: cant find build path: \"$BUILD_PATH\""
    exit
fi


echo "Changing stable symlink ($BUILD_NAME)"
ln -s $BUILD_PATH new-genome-stable
mv -Tf new-genome-stable genome-stable


echo "Changing web symlink (needs a restart)"
ln -s $BUILD_PATH new-genome-webapp
mv -Tf new-genome-webapp genome-webapp


perl $HUDSON_CODE_PATH/tools/changelog.pl $OLD_BUILD_NAME $NEW_BUILD_NAME > $DEPLOY_PATH/CHANGES
echo "Subject: Changes for $NEW_BUILD_NAME " | cat - $DEPLOY_PATH/CHANGES | sendmail -F apipe-tester@genome.wustl.edu -t apipe@genome.wustl.edu



# /gsc/scripts/lib



